language: python
python:
  - "2.6"
  - "2.7"
  # - "3.4"

branches:
  only:
    - master
    - develop
    - /^release-.*$/

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libblas-dev liblapack-dev libatlas-base-dev gfortran

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script: py.test test/

